package cn.edu.app.douyu.ui.theme

import androidx.compose.ui.graphics.Color

// ── Brand Colors (shared across light/dark) ──
val DoyuPetal = Color(0xFFF48FA4)
val DoyuCoral = Color(0xFFFF8F75)
val DoyuMint = Color(0xFFA8DCC6)
val DoyuSky = Color(0xFF9EC9F5)

// ── Light Theme Palette ──
val LightPrimary = Color(0xFFE8778E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFE0E6)
val LightOnPrimaryContainer = Color(0xFF3B0714)
val LightSecondary = Color(0xFF7DB89A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD4F0E0)
val LightOnSecondaryContainer = Color(0xFF0A2016)
val LightTertiary = Color(0xFF7AADE0)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD6E8FF)
val LightOnTertiaryContainer = Color(0xFF0A1A2E)
val LightBackground = Color(0xFFFFFBF7)
val LightOnBackground = Color(0xFF201A1C)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF201A1C)
val LightSurfaceVariant = Color(0xFFFFF0F3)
val LightOnSurfaceVariant = Color(0xFF524347)
val LightOutline = Color(0xFFE0CDD0)
val LightOutlineVariant = Color(0xFFF5DDE1)
val LightError = Color(0xFFD95F6A)
val LightOnError = Color(0xFFFFFFFF)
val LightSuccess = Color(0xFF5AAE7A)
val LightWarning = Color(0xFFE9934C)

// ── Dark Theme Palette ──
val DarkPrimary = Color(0xFFFFB1C1)
val DarkOnPrimary = Color(0xFF5E1126)
val DarkPrimaryContainer = Color(0xFF8B2E42)
val DarkOnPrimaryContainer = Color(0xFFFFE0E6)
val DarkSecondary = Color(0xFFA0D4B8)
val DarkOnSecondary = Color(0xFF0F3526)
val DarkSecondaryContainer = Color(0xFF2A5A42)
val DarkOnSecondaryContainer = Color(0xFFD4F0E0)
val DarkTertiary = Color(0xFFA8CAEF)
val DarkOnTertiary = Color(0xFF0F2F4A)
val DarkTertiaryContainer = Color(0xFF2A4A68)
val DarkOnTertiaryContainer = Color(0xFFD6E8FF)
val DarkBackground = Color(0xFF1A1215)
val DarkOnBackground = Color(0xFFF0E0E3)
val DarkSurface = Color(0xFF241C1F)
val DarkOnSurface = Color(0xFFF0E0E3)
val DarkSurfaceVariant = Color(0xFF322829)
val DarkOnSurfaceVariant = Color(0xFFD7C1C5)
val DarkOutline = Color(0xFF9F8C90)
val DarkOutlineVariant = Color(0xFF524347)
val DarkError = Color(0xFFFFB3B3)
val DarkOnError = Color(0xFF3A0808)
val DarkSuccess = Color(0xFF8FD4A6)
val DarkWarning = Color(0xFFFFCF99)
